export const initialTableData = [
    {
        "header": {
            "slNo": "INV-2023-001",
            "internalNumber": "INT-789456",
            "taxInvoice": "TAX-INV-2023-789",
            "invoiceDateTime": "2023-11-15T14:30:00",
            "referenceDocument": "PO-2023-456",
            "regNo": "REG-789123",
            "customerID": "CUST-45678",
            "billToGSTIN": "22ABCDE1234F1Z5",
            "detailsOfReceiver": "ABC Motors Pvt Ltd",
            "taxableValue": 18500.00,
            "cgstAmount": 1665.00,
            "sgstAmount": 1665.00,
            "igstAmount": 0.00,
            "totalInvoiceValue": 21830.00,
            "fileName": "INV_2023_789.pdf",
            "registerNumber": "MH-01-AB-1234",
            "invoiceNumber": "INV-2023-789",
            "fullModelCode": "SUV-XLT-2023",
            "vinNo": "MA3EDL12345678901",
            "engineNo": "ENG2023XYZ789456",
            "jobType": "Regular Service",
            "placeOfSupply": "Maharashtra",
            "contactName": "Rahul Sharma",
            "contactPhone": "9876543210",
            "customerBillTo": "ABC Motors, Mumbai",
            "customerShipTo": "ABC Motors, Andheri East",
            "gstin": "22ABCDE1234F1Z5",
            "invoiceType": "Tax Invoice",
            "branchCode": "BR-MUM-001"
        },
        "lineItems": [
            {
                "type": "Part",
                "partNo": "FILT-OIL-001",
                "description": "Engine Oil Filter (Premium)",
                "hsn": "84212390",
                "quantity": 2,
                "uom": "NOS",
                "unitPrice": 1200.00,
                "discountPercent": 10,
                "discountAmount": 240.00,
                "taxableValue": 2160.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 194.40,
                "sgstAmount": 194.40,
                "igstAmount": 0.00,
                "amountWithTax": 2548.80
            },
            {
                "type": "Part",
                "partNo": "OIL-SYN-5W30",
                "description": "Synthetic Engine Oil 5W-30 (4L)",
                "hsn": "27101980",
                "quantity": 4,
                "uom": "LTR",
                "unitPrice": 950.00,
                "discountPercent": 5,
                "discountAmount": 190.00,
                "taxableValue": 3610.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 324.90,
                "sgstAmount": 324.90,
                "igstAmount": 0.00,
                "amountWithTax": 4259.80
            }
        ]
    },
    {
        "header": {
            "slNo": "INV-2023-002",
            "internalNumber": "INT-987123",
            "taxInvoice": "TAX-INV-2023-987",
            "invoiceDateTime": "2023-11-16T10:15:00",
            "referenceDocument": "WO-2023-789",
            "regNo": "KA-05-EF-5678",
            "customerID": "CUST-78901",
            "billToGSTIN": "29BBAXE8765G2Z9",
            "detailsOfReceiver": "XYZ Autoworks",
            "taxableValue": 32450.00,
            "cgstAmount": 0.00,
            "sgstAmount": 0.00,
            "igstAmount": 5841.00,
            "totalInvoiceValue": 38291.00,
            "fileName": "INV_2023_987.pdf",
            "registerNumber": "KA-05-EF-5678",
            "invoiceNumber": "INV-2023-987",
            "fullModelCode": "SED-LX-2022",
            "vinNo": "MA1FDS98765432109",
            "engineNo": "ENG2022ABC456123",
            "jobType": "Accident Repair",
            "placeOfSupply": "Karnataka",
            "contactName": "Priya Patel",
            "contactPhone": "8765432109",
            "customerBillTo": "XYZ Autoworks, Bangalore",
            "customerShipTo": "XYZ Autoworks, Whitefield",
            "gstin": "29BBAXE8765G2Z9",
            "invoiceType": "Tax Invoice",
            "branchCode": "BR-BLR-003"
        },
        "lineItems": [
            {
                "type": "Part",
                "partNo": "BRK-PAD-FR",
                "description": "Front Brake Pads (Set)",
                "hsn": "87083090",
                "quantity": 1,
                "uom": "SET",
                "unitPrice": 4500.00,
                "discountPercent": 0,
                "discountAmount": 0.00,
                "taxableValue": 4500.00,
                "cgstRate": 0,
                "sgstRate": 0,
                "igstRate": 18,
                "cgstAmount": 0.00,
                "sgstAmount": 0.00,
                "igstAmount": 810.00,
                "amountWithTax": 5310.00
            },
            {
                "type": "Part",
                "partNo": "WNDSHD-ASIAN",
                "description": "Front Windshield (OEM)",
                "hsn": "70072100",
                "quantity": 1,
                "uom": "NOS",
                "unitPrice": 18500.00,
                "discountPercent": 10,
                "discountAmount": 1850.00,
                "taxableValue": 16650.00,
                "cgstRate": 0,
                "sgstRate": 0,
                "igstRate": 18,
                "cgstAmount": 0.00,
                "sgstAmount": 0.00,
                "igstAmount": 2997.00,
                "amountWithTax": 19647.00
            },
            {
                "type": "Service",
                "partNo": "PAINT-LAB",
                "description": "Paint & Refinishing",
                "hsn": "998813",
                "quantity": 1,
                "uom": "JOB",
                "unitPrice": 11300.00,
                "discountPercent": 0,
                "discountAmount": 0.00,
                "taxableValue": 11300.00,
                "cgstRate": 0,
                "sgstRate": 0,
                "igstRate": 18,
                "cgstAmount": 0.00,
                "sgstAmount": 0.00,
                "igstAmount": 2034.00,
                "amountWithTax": 13334.00
            }
        ]
    },
    {
        "header": {
            "slNo": "INV-2023-003",
            "internalNumber": "INT-654789",
            "taxInvoice": "TAX-INV-2023-654",
            "invoiceDateTime": "2023-11-17T16:45:00",
            "referenceDocument": "SO-2023-321",
            "regNo": "DL-03-CD-9012",
            "customerID": "CUST-12345",
            "billToGSTIN": "07PPPLS4321R1Z3",
            "detailsOfReceiver": "Delhi Auto Care",
            "taxableValue": 8720.00,
            "cgstAmount": 784.80,
            "sgstAmount": 784.80,
            "igstAmount": 0.00,
            "totalInvoiceValue": 10289.60,
            "fileName": "INV_2023_654.pdf",
            "registerNumber": "DL-03-CD-9012",
            "invoiceNumber": "INV-2023-654",
            "fullModelCode": "HATCH-ZX-2021",
            "vinNo": "MA0JKL45678901234",
            "engineNo": "ENG2021DEF123789",
            "jobType": "Periodic Maintenance",
            "placeOfSupply": "Delhi",
            "contactName": "Amit Singh",
            "contactPhone": "7654321098",
            "customerBillTo": "Delhi Auto Care, Noida",
            "customerShipTo": "Delhi Auto Care, Sector-62",
            "gstin": "07PPPLS4321R1Z3",
            "invoiceType": "Tax Invoice",
            "branchCode": "BR-DEL-005"
        },
        "lineItems": [
            {
                "type": "Part",
                "partNo": "AIR-FIL-CAB",
                "description": "Cabin Air Filter",
                "hsn": "84213100",
                "quantity": 1,
                "uom": "NOS",
                "unitPrice": 850.00,
                "discountPercent": 15,
                "discountAmount": 127.50,
                "taxableValue": 722.50,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 65.03,
                "sgstAmount": 65.03,
                "igstAmount": 0.00,
                "amountWithTax": 852.56
            },
            {
                "type": "Part",
                "partNo": "SPRK-PLUG4",
                "description": "Iridium Spark Plug (Set of 4)",
                "hsn": "85111090",
                "quantity": 1,
                "uom": "SET",
                "unitPrice": 3200.00,
                "discountPercent": 10,
                "discountAmount": 320.00,
                "taxableValue": 2880.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 259.20,
                "sgstAmount": 259.20,
                "igstAmount": 0.00,
                "amountWithTax": 3398.40
            },
            {
                "type": "Service",
                "partNo": "LAB-60K",
                "description": "60,000 km Service Package",
                "hsn": "998719",
                "quantity": 1,
                "uom": "JOB",
                "unitPrice": 6500.00,
                "discountPercent": 5,
                "discountAmount": 325.00,
                "taxableValue": 6175.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 555.75,
                "sgstAmount": 555.75,
                "igstAmount": 0.00,
                "amountWithTax": 7286.50
            },
            {
                "type": "Part",
                "partNo": "AIR-FIL-CAB",
                "description": "Cabin Air Filter",
                "hsn": "84213100",
                "quantity": 1,
                "uom": "NOS",
                "unitPrice": 850.00,
                "discountPercent": 15,
                "discountAmount": 127.50,
                "taxableValue": 722.50,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 65.03,
                "sgstAmount": 65.03,
                "igstAmount": 0.00,
                "amountWithTax": 852.56
            },
            {
                "type": "Part",
                "partNo": "SPRK-PLUG4",
                "description": "Iridium Spark Plug (Set of 4)",
                "hsn": "85111090",
                "quantity": 1,
                "uom": "SET",
                "unitPrice": 3200.00,
                "discountPercent": 10,
                "discountAmount": 320.00,
                "taxableValue": 2880.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 259.20,
                "sgstAmount": 259.20,
                "igstAmount": 0.00,
                "amountWithTax": 3398.40
            },
            {
                "type": "Service",
                "partNo": "LAB-60K",
                "description": "60,000 km Service Package",
                "hsn": "998719",
                "quantity": 1,
                "uom": "JOB",
                "unitPrice": 6500.00,
                "discountPercent": 5,
                "discountAmount": 325.00,
                "taxableValue": 6175.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 555.75,
                "sgstAmount": 555.75,
                "igstAmount": 0.00,
                "amountWithTax": 7286.50
            },
            {
                "type": "Part",
                "partNo": "AIR-FIL-CAB",
                "description": "Cabin Air Filter",
                "hsn": "84213100",
                "quantity": 1,
                "uom": "NOS",
                "unitPrice": 850.00,
                "discountPercent": 15,
                "discountAmount": 127.50,
                "taxableValue": 722.50,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 65.03,
                "sgstAmount": 65.03,
                "igstAmount": 0.00,
                "amountWithTax": 852.56
            },
            {
                "type": "Part",
                "partNo": "SPRK-PLUG4",
                "description": "Iridium Spark Plug (Set of 4)",
                "hsn": "85111090",
                "quantity": 1,
                "uom": "SET",
                "unitPrice": 3200.00,
                "discountPercent": 10,
                "discountAmount": 320.00,
                "taxableValue": 2880.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 259.20,
                "sgstAmount": 259.20,
                "igstAmount": 0.00,
                "amountWithTax": 3398.40
            },
            {
                "type": "Service",
                "partNo": "LAB-60K",
                "description": "60,000 km Service Package",
                "hsn": "998719",
                "quantity": 1,
                "uom": "JOB",
                "unitPrice": 6500.00,
                "discountPercent": 5,
                "discountAmount": 325.00,
                "taxableValue": 6175.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 555.75,
                "sgstAmount": 555.75,
                "igstAmount": 0.00,
                "amountWithTax": 7286.50
            },
            {
                "type": "Part",
                "partNo": "AIR-FIL-CAB",
                "description": "Cabin Air Filter",
                "hsn": "84213100",
                "quantity": 1,
                "uom": "NOS",
                "unitPrice": 850.00,
                "discountPercent": 15,
                "discountAmount": 127.50,
                "taxableValue": 722.50,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 65.03,
                "sgstAmount": 65.03,
                "igstAmount": 0.00,
                "amountWithTax": 852.56
            },
            {
                "type": "Part",
                "partNo": "SPRK-PLUG4",
                "description": "Iridium Spark Plug (Set of 4)",
                "hsn": "85111090",
                "quantity": 1,
                "uom": "SET",
                "unitPrice": 3200.00,
                "discountPercent": 10,
                "discountAmount": 320.00,
                "taxableValue": 2880.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 259.20,
                "sgstAmount": 259.20,
                "igstAmount": 0.00,
                "amountWithTax": 3398.40
            },
            {
                "type": "Service",
                "partNo": "LAB-60K",
                "description": "60,000 km Service Package",
                "hsn": "998719",
                "quantity": 1,
                "uom": "JOB",
                "unitPrice": 6500.00,
                "discountPercent": 5,
                "discountAmount": 325.00,
                "taxableValue": 6175.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 555.75,
                "sgstAmount": 555.75,
                "igstAmount": 0.00,
                "amountWithTax": 7286.50
            },
            {
                "type": "Part",
                "partNo": "AIR-FIL-CAB",
                "description": "Cabin Air Filter",
                "hsn": "84213100",
                "quantity": 1,
                "uom": "NOS",
                "unitPrice": 850.00,
                "discountPercent": 15,
                "discountAmount": 127.50,
                "taxableValue": 722.50,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 65.03,
                "sgstAmount": 65.03,
                "igstAmount": 0.00,
                "amountWithTax": 852.56
            },
            {
                "type": "Part",
                "partNo": "SPRK-PLUG4",
                "description": "Iridium Spark Plug (Set of 4)",
                "hsn": "85111090",
                "quantity": 1,
                "uom": "SET",
                "unitPrice": 3200.00,
                "discountPercent": 10,
                "discountAmount": 320.00,
                "taxableValue": 2880.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 259.20,
                "sgstAmount": 259.20,
                "igstAmount": 0.00,
                "amountWithTax": 3398.40
            },
            {
                "type": "Service",
                "partNo": "LAB-60K",
                "description": "60,000 km Service Package",
                "hsn": "998719",
                "quantity": 1,
                "uom": "JOB",
                "unitPrice": 6500.00,
                "discountPercent": 5,
                "discountAmount": 325.00,
                "taxableValue": 6175.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 555.75,
                "sgstAmount": 555.75,
                "igstAmount": 0.00,
                "amountWithTax": 7286.50
            },
            {
                "type": "Part",
                "partNo": "AIR-FIL-CAB",
                "description": "Cabin Air Filter",
                "hsn": "84213100",
                "quantity": 1,
                "uom": "NOS",
                "unitPrice": 850.00,
                "discountPercent": 15,
                "discountAmount": 127.50,
                "taxableValue": 722.50,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 65.03,
                "sgstAmount": 65.03,
                "igstAmount": 0.00,
                "amountWithTax": 852.56
            },
            {
                "type": "Part",
                "partNo": "SPRK-PLUG4",
                "description": "Iridium Spark Plug (Set of 4)",
                "hsn": "85111090",
                "quantity": 1,
                "uom": "SET",
                "unitPrice": 3200.00,
                "discountPercent": 10,
                "discountAmount": 320.00,
                "taxableValue": 2880.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 259.20,
                "sgstAmount": 259.20,
                "igstAmount": 0.00,
                "amountWithTax": 3398.40
            },
            {
                "type": "Service",
                "partNo": "LAB-60K",
                "description": "60,000 km Service Package",
                "hsn": "998719",
                "quantity": 1,
                "uom": "JOB",
                "unitPrice": 6500.00,
                "discountPercent": 5,
                "discountAmount": 325.00,
                "taxableValue": 6175.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 555.75,
                "sgstAmount": 555.75,
                "igstAmount": 0.00,
                "amountWithTax": 7286.50
            },
            {
                "type": "Part",
                "partNo": "AIR-FIL-CAB",
                "description": "Cabin Air Filter",
                "hsn": "84213100",
                "quantity": 1,
                "uom": "NOS",
                "unitPrice": 850.00,
                "discountPercent": 15,
                "discountAmount": 127.50,
                "taxableValue": 722.50,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 65.03,
                "sgstAmount": 65.03,
                "igstAmount": 0.00,
                "amountWithTax": 852.56
            },
            {
                "type": "Part",
                "partNo": "SPRK-PLUG4",
                "description": "Iridium Spark Plug (Set of 4)",
                "hsn": "85111090",
                "quantity": 1,
                "uom": "SET",
                "unitPrice": 3200.00,
                "discountPercent": 10,
                "discountAmount": 320.00,
                "taxableValue": 2880.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 259.20,
                "sgstAmount": 259.20,
                "igstAmount": 0.00,
                "amountWithTax": 3398.40
            },
            {
                "type": "Service",
                "partNo": "LAB-60K",
                "description": "60,000 km Service Package",
                "hsn": "998719",
                "quantity": 1,
                "uom": "JOB",
                "unitPrice": 6500.00,
                "discountPercent": 5,
                "discountAmount": 325.00,
                "taxableValue": 6175.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 555.75,
                "sgstAmount": 555.75,
                "igstAmount": 0.00,
                "amountWithTax": 7286.50
            },
            {
                "type": "Part",
                "partNo": "AIR-FIL-CAB",
                "description": "Cabin Air Filter",
                "hsn": "84213100",
                "quantity": 1,
                "uom": "NOS",
                "unitPrice": 850.00,
                "discountPercent": 15,
                "discountAmount": 127.50,
                "taxableValue": 722.50,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 65.03,
                "sgstAmount": 65.03,
                "igstAmount": 0.00,
                "amountWithTax": 852.56
            },
            {
                "type": "Part",
                "partNo": "SPRK-PLUG4",
                "description": "Iridium Spark Plug (Set of 4)",
                "hsn": "85111090",
                "quantity": 1,
                "uom": "SET",
                "unitPrice": 3200.00,
                "discountPercent": 10,
                "discountAmount": 320.00,
                "taxableValue": 2880.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 259.20,
                "sgstAmount": 259.20,
                "igstAmount": 0.00,
                "amountWithTax": 3398.40
            },
            {
                "type": "Service",
                "partNo": "LAB-60K",
                "description": "60,000 km Service Package",
                "hsn": "998719",
                "quantity": 1,
                "uom": "JOB",
                "unitPrice": 6500.00,
                "discountPercent": 5,
                "discountAmount": 325.00,
                "taxableValue": 6175.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 555.75,
                "sgstAmount": 555.75,
                "igstAmount": 0.00,
                "amountWithTax": 7286.50
            },
            {
                "type": "Part",
                "partNo": "AIR-FIL-CAB",
                "description": "Cabin Air Filter",
                "hsn": "84213100",
                "quantity": 1,
                "uom": "NOS",
                "unitPrice": 850.00,
                "discountPercent": 15,
                "discountAmount": 127.50,
                "taxableValue": 722.50,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 65.03,
                "sgstAmount": 65.03,
                "igstAmount": 0.00,
                "amountWithTax": 852.56
            },
            {
                "type": "Part",
                "partNo": "SPRK-PLUG4",
                "description": "Iridium Spark Plug (Set of 4)",
                "hsn": "85111090",
                "quantity": 1,
                "uom": "SET",
                "unitPrice": 3200.00,
                "discountPercent": 10,
                "discountAmount": 320.00,
                "taxableValue": 2880.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 259.20,
                "sgstAmount": 259.20,
                "igstAmount": 0.00,
                "amountWithTax": 3398.40
            },
            {
                "type": "Service",
                "partNo": "LAB-60K",
                "description": "60,000 km Service Package",
                "hsn": "998719",
                "quantity": 1,
                "uom": "JOB",
                "unitPrice": 6500.00,
                "discountPercent": 5,
                "discountAmount": 325.00,
                "taxableValue": 6175.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 555.75,
                "sgstAmount": 555.75,
                "igstAmount": 0.00,
                "amountWithTax": 7286.50
            },
            {
                "type": "Part",
                "partNo": "AIR-FIL-CAB",
                "description": "Cabin Air Filter",
                "hsn": "84213100",
                "quantity": 1,
                "uom": "NOS",
                "unitPrice": 850.00,
                "discountPercent": 15,
                "discountAmount": 127.50,
                "taxableValue": 722.50,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 65.03,
                "sgstAmount": 65.03,
                "igstAmount": 0.00,
                "amountWithTax": 852.56
            },
            {
                "type": "Part",
                "partNo": "SPRK-PLUG4",
                "description": "Iridium Spark Plug (Set of 4)",
                "hsn": "85111090",
                "quantity": 1,
                "uom": "SET",
                "unitPrice": 3200.00,
                "discountPercent": 10,
                "discountAmount": 320.00,
                "taxableValue": 2880.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 259.20,
                "sgstAmount": 259.20,
                "igstAmount": 0.00,
                "amountWithTax": 3398.40
            },
            {
                "type": "Service",
                "partNo": "LAB-60K",
                "description": "60,000 km Service Package",
                "hsn": "998719",
                "quantity": 1,
                "uom": "JOB",
                "unitPrice": 6500.00,
                "discountPercent": 5,
                "discountAmount": 325.00,
                "taxableValue": 6175.00,
                "cgstRate": 9,
                "sgstRate": 9,
                "igstRate": 0,
                "cgstAmount": 555.75,
                "sgstAmount": 555.75,
                "igstAmount": 0.00,
                "amountWithTax": 7286.50
            }
        ]
    }
];